### ISSUE TITLE
Loading a save: all trains are halted.

### ISSUE THREAD

**Issue by Elektri4ker** [xmnovotny/VoxelTycoon-AdvancedPathfinder#1]
They display some speed in their info, but they are not moving.
And 'bug' displayed. Here follows the log.
[Player.log](https://github.com/xmnovotny/VoxelTycoon-AdvancedPathfinder/files/6945887/Player.log)

The save:
https://drive.google.com/file/d/1GaeDaJ2R2lkTw4Lhh-kltnOo3YtBn8Ri/view?usp=sharing

game version:
0.86.1

Another mods installed:
* Cap remover

**Comment by xmnovotny** [comment]
I don't see any bugs in the Player.log. Maybe you have restarted game before sending me a file?
And could I ask you for a save file?

**Comment by Elektri4ker** [comment]
> 
> 
> I don't see any bugs in the Player.log. Maybe you have restarted game before sending me a file?
> And could I ask you for a save file?

Yes, you were right. I updated my first message with the correct log and with the save as well.

**Comment by xmnovotny** [comment]
Fixed in the 0.94 beta version.
And much thanks for reporting and providing such a complex railway network in the save.
