### ISSUE TITLE
Trains stuck at signals occasionally

### ISSUE THREAD

**Issue by Elektri4ker** [xmnovotny/VoxelTycoon-AdvancedPathfinder#3]
Hello, it's me again!
Good mod for playing so far!

So I found another issue after upgrading the mod to 1.0. Playing my map.
Trains stuck at a signal and do not proceed. They do not reserve a way either.
When I restart the game, all stuck trains proceed behind stale signals, but after running the game for a while, another train(s) get stuck.
In this [save](https://drive.google.com/file/d/1vNU-b18cwhMNoG9C3CO6f3BxzMX8nmcJ/view?usp=sharing), you may find "Train #46" on the screen proceeds after being stuck. But then you may follow 'Train #8' which will stuck soon.
I tried to disable the mod, run the game for a while and then enable it again, but got the same issue again.

+ Bonus:
In this [save](https://drive.google.com/file/d/10uNBZWD-gjd605PM0wIcwi2MN8Kuk9PI/view?usp=sharing), just after loading the save, "Train #45" proceeds without reserving a way. What leads to a train accident. At the snapshot, "Train #45" had speed 97km/h but have not passed behind the signal yet.

**Comment by xmnovotny** [comment]
Thanks for the report. I'll take a look at it in a few days and hopefully fix the problem.

**Comment by xmnovotny** [comment]
Fixed in 1.0.1, please test it if it works at your computer. Thanks.
