### ISSUE TITLE
Train wreckage due to unreserved block

### ISSUE THREAD

**Issue by Elektri4ker** [xmnovotny/VoxelTycoon-AdvancedPathfinder#4]
Hi!
Train #45 does not reserve a block which is shown on this screenshot:
![20210828145836_1](https://user-images.githubusercontent.com/8113198/131218908-43a7dcef-8c62-4c9b-9e0a-5b179414d5cf.jpg)

This leads to a crash with Train #38 soon.

[Save](https://drive.google.com/file/d/1GaeDaJ2R2lkTw4Lhh-kltnOo3YtBn8Ri/view?usp=sharing)

**Comment by xmnovotny** [comment]
Thank for the report. I have tried it several times in the new version and no problem with path reservation.
But there was a reservation bug after the train was forced to change path or reverse direction. Maybe it was the cause.

**Comment by Elektri4ker** [comment]
I've tried it on this save and there are no problems now. Thanks for your support!
