### ISSUE TITLE
Game crashes every time at the same train position

### ISSUE THREAD

**Issue by Livedeath2k** [xmnovotny/VoxelTycoon-AdvancedPathfinder#5]
Hi.
I use your mods and i get a game crash everytime my train travels to a specific position on the map.
Can you please check if one your mod have a bug?
Because the other mods i use so far are running smooth before i added your mods.
I added the save as compressed zip file.
Thank you :-)

[Player.log](https://github.com/xmnovotny/VoxelTycoon-AdvancedPathfinder/files/7072967/Player.log)
[yp5kyg0oo2c.zip](https://github.com/xmnovotny/VoxelTycoon-AdvancedPathfinder/files/7072961/yp5kyg0oo2c.zip)

**Comment by xmnovotny** [comment]
Thank you for detailed info. Confirming that bug, so now I will investigate the cause and then it will be fixed in the next version as soon as possible.

**Comment by xmnovotny** [comment]
Ok, one "your" bug solved, another two serious found :-)

**Comment by Livedeath2k** [comment]
Nice.Oh 2 more bugs found?Interesting.Thank you for trying to fix them. ☺️Am 30.08.2021 22:52 schrieb xmnovotny ***@***.***>:
Ok, one "your" bug solved, another two serious found :-)

**Comment by xmnovotny** [comment]
Hopefully everything is fixed now. You can try.
